cmake_minimum_required(VERSION 3.25)

project(elite)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_FLAGS "-Wall")
set(SRC_PATH ${PROJECT_SOURCE_DIR}/src)

include_directories(src)

add_subdirectory(src/array)
add_subdirectory(src/binary_tree_general)
add_subdirectory(src/binary_search_tree)
add_subdirectory(src/DP1D)
add_subdirectory(src/hashmap)
add_subdirectory(src/heap)
add_subdirectory(src/intervals)
add_subdirectory(src/linked_list)
add_subdirectory(src/math)
add_subdirectory(src/matrix)
add_subdirectory(src/sliding_window)
add_subdirectory(src/stack)
add_subdirectory(src/two_pointers)
